# Setup
title:        Movies as a graph
tagline:      Project ADA 2022
baseurl:      "https://leondelachaux.github.io/ada_website_cayman"
paginate:     1
locale:       "en"
# https://leondelachaux.github.io/ada_website_cayman
# About/contact
author:
  name: Camille Guillaume, Taras Pavliv, Yucef Grebici, Léon Delachaux
  url:            

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
